---
title: "2021_33"
author: "Danilo De Rosa"
date: "8/12/2021"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load-libraries}
library(tidyverse)
library(ggtext)
library(ggstream)
library(showtext)
library(waffle)
library(patchwork)

font_add_google("Anton", "anton")
showtext_auto()
```


```{r load-prep-data}
chain_investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/chain_investment.csv', col_types = list(
  category = col_factor(), # better if it's a factor
  meta_cat = col_factor(), # like above
  group_num = col_double(),
  year = col_double(),
  gross_inv_chain = col_double()))

```

```{r}
digital <- chain_investment %>%
  filter(meta_cat == "Digital" & year %in% c("1967", "1980", "1990", "2000", "2010", "2017")) %>% 
  group_by(year, category) %>% 
  summarise(total = sum(gross_inv_chain)) %>%
  mutate(prop = round((total / sum(total))*100), 
         category_label = case_when(
          category == "Private computers in NAICS 515, 517, 518, and 519"~"Computers",
          category == "Private software in NAICS 515, 517, 518, and 519"~"Software",
          category == "Private communications equipment in NAICS 515, 517, 518, and 519"~"Com. equipment",
          category == "Private communications structures"~"Com. structures"
         ))
  
```

```{r}
total_inv <- chain_investment %>% 
  filter(group_num == 1) %>% 
  mutate(cat = factor(case_when(
    category == "Total basic infrastructure" ~ "Basic", 
    category == "Total social infrastructure" ~ "Social",
    category == "Total digital infrastructure" ~ "Digital"
  ))) 


category_label <- c("Basic", "Social", "Digital")

total_inv$cat <- fct_relevel(total_inv$cat, "Digital", after = 1)

plot1 <- total_inv %>% 
  ggplot(aes(year, gross_inv_chain, 
             fill = cat, 
             alpha = cat == "Digital")) + 
  geom_stream(
    type = "mirror", 
    bw = .5
  ) +
  annotate("text", 
           x = 1971, y = 230000, label = "Basic \nInfrastructure", 
           color = "#FF8C00", alpha = .5, size = rel(10), lineheight = .7, fontface = "italic", angle = 8
             ) +
  annotate("text", 
           x = 1971, y = -230000, label = "Social \nInfrastructure", 
           color = "#159090", alpha = .5, size = rel(10), lineheight = .7, fontface = "italic", angle = -8
             ) +
  annotate("text", 
           x = 1983, y = 10000, label = "Digital \nInfrastructure", 
           color = "#A034F0", size = rel(10), lineheight = .8, fontface = "italic"
             ) +
  annotate("text", 
           x = 2023.5, y = 190000, label = "2017: \n306 bln $", color = "#FF8C00", size = rel(6), lineheight = .8, alpha = .5) + 
  annotate("text", 
           x = 2023.5, y = -240000, label = "2017: \n247 bln $", color = "#159090", size = rel(6), lineheight = .8, alpha = .5) + 
  annotate("text", 
           x = 2023.5, y = -24000, label = "2017: \n245 bln $", color = "#A034F0", size = rel(6), lineheight = .8) + 
  annotate("text", 
           x = 2043, 
           y = 250000,
           label = "Communication \nstructures", 
           color = "#420039", 
           size = rel(6), 
           lineheight = .8) + 
  annotate("text", 
           x = 2043, 
           y = 18000,
           label = "Communication \nequipment", 
           color = "#C07AF5", 
           size = rel(6), 
           lineheight = .8) + 
  annotate("text", 
           x = 2043, 
           y = -230000,
           label = "Software", 
           color = "#DBB3F9", 
           size = rel(6), 
           lineheight = .8) + 
  annotate("text", 
           x = 2043, 
           y = -185000,
           label = "Computers", 
           color = "#C7ADFF", 
           size = rel(6), 
           lineheight = .8) + 
  scale_fill_manual(values = c("#FF8C00", "#A034F0", "#159090"), guide = "none") +
  scale_alpha_manual(values = c(.2, 1), guide = "none") +
  scale_x_continuous(breaks = c(1950, 1965, 1980, 1995, 2010), limits = c(NA, 2045)) +
  theme_minimal(base_size = 20, base_family = "anton") +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_blank(), 
        axis.text.x = element_text(face = "plain"),
        plot.margin = margin(20, 10, 20, 0),
        plot.subtitle = element_markdown(size = rel(.8), hjust = .3)) +
  labs(subtitle = "Investment in US infrastructure (chained 2021 $)")
```

  
```{r plot2}
digital$prop[digital$year == 1980 & digital$category_label == "Software"] <- 0

plot2 <- digital %>% 
  filter(year %in% c(1980, 2000, 2017)) %>% 
  ggplot(aes(fill = category_label, values = prop)) + 
  geom_waffle(color = "white", n_rows = 10, flip = T) +
  facet_wrap(~year, ncol = 1) +
  theme_void(base_family = "anton") +
  scale_fill_manual(values = c( "#C07AF5", "#420039", "#DCCCFF", "#DBB3F9")) +
  guides(fill = "none") +
  theme(plot.margin = margin(20, 20, 20, 0),
        strip.text = element_text(face = "bold", size = rel(1.5)),
        plot.caption = element_markdown(size = rel(1.3), margin = margin(5, 0, 10, 0)),
        plot.subtitle = element_markdown(size = rel(1.3))) +
  labs(subtitle = "&#37; of digital investment, \nby category",
       caption = "Data: Bureau of Economics Analysis &bull; TidyTuesday 2021/33")

```


```{r}
plot1 + plot2 + patchwork::plot_layout(widths = c(2, .5)) + patchwork::plot_annotation(title = "US Investments goes <span style='color:#A034F0'>digital</span>", theme = theme(
  plot.background = element_rect(fill = "grey90", color = "grey90"),
  plot.title = element_markdown(hjust = .5, family = "anton", size = rel(5),
                                margin = margin(30, 0, 30, 0))))

path <- here::here("plots", "2021_33", "2021_BEAInfrastructureInvestments")
ggsave(glue::glue("{path}.pdf"), width = 16, height = 10, device = cairo_pdf)
pdftools::pdf_convert(pdf = glue::glue("{path}.pdf"), 
                      filenames = glue::glue("{path}.png"),
                      format = "png", dpi = 300)

```


