---
title: "2021_32"
author: "Danilo De Rosa"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.retina = 1)
```


```{r data-libraries}
library(tidyverse)
library(ggtext)
library(ggflags) # install with devtools::install_github('rensa/ggflags')
library(countrycode)
library(showtext)

font_add_google("Jetbrains Mono", "jetbrains")
showtext_auto()

athletes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-03/athletes.csv')

athletes <- athletes %>% 
  mutate(abb = case_when(abb == "URS" ~ "RUS",
                         abb == "EUN" ~ "RUS",
                         abb == "FRG" ~ "DEU",
                         abb == "GER" ~ "DEU",
                         abb == "NED" ~ "NLD",
                         abb == "DEN" ~ "DNK",
                         abb == "IRI" ~ "IRN",
                         abb == "RSA" ~ "ZAF",
                         TRUE ~ abb))

gold_medal <- athletes %>% 
  filter(medal == "Gold") %>%
  distinct(gender, event, year, type, abb) %>% 
  group_by(year) %>% 
  count(abb) %>% 
  arrange(year, desc(n)) %>% 
  group_by(year) %>% 
  mutate(rank = row_number()) %>% 
  filter(rank <= 10) %>% 
  mutate(iso2=tolower(countrycode(abb, "iso3c", "iso2c")))
```


```{r fig.height=8, fig.width=10, message=FALSE}
plot <- gold_medal %>% 
  ggplot(aes(factor(year), fct_rev(as.factor(rank)), color = abb)) +
  geom_point(shape=21,colour="black",size=15.5) +
  geom_flag(aes(country = iso2), size = 13.5) +
  theme_minimal(base_family = "jetbrains") +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_text(size = rel(1.3)),
        axis.text.x = element_text(margin = margin(t = 10)),
        plot.title = element_markdown(hjust = .5, margin = margin(b = 8)),
        plot.subtitle = element_text(hjust = -.03, vjust = -1, size = 15),
        plot.caption = element_markdown(margin = margin(t = 20)),
        plot.margin = margin(20, 10, 20, 20)) +
  labs(title = "<span style='font-size:40pt'>Paralympic <span style='color:#DAA520'>Gold</span></span> <br><br> <span style='font-size:15pt'>Best 10 countries in each Paralympic Olympics based on gold medals</span>",
       subtitle = "Rank",
       caption = "Data: International Paralympic Committee &bull; TidyTuesday 2021/32")

path <- here::here("plots", "2021_32", "2021_ParalympicMedals")
ggsave(glue::glue("{path}.pdf"), plot = plot, width = 10, height = 8, device = cairo_pdf)
pdftools::pdf_convert(pdf = glue::glue("{path}.pdf"), 
                      filenames = glue::glue("{path}.png"),
                      format = "png", dpi = 450)
```

